//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prakt18
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManySalesDB : DbContext
    {
        public ManySalesDB()
            : base("name=ManySalesDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        private static ManySalesDB context;
        public static ManySalesDB GetContext()
        {
            if (context == null)
                context = new ManySalesDB();
            return context;
        }
        public virtual DbSet<Sales> Sales { get; set; }
    }
}
