//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prakt18
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> SinglePrice { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<int> BatchNumber { get; set; }
        public Nullable<int> BatchSize { get; set; }
        public string BuyerCompany { get; set; }
        public Nullable<int> SelledBatchSize { get; set; }
        public Nullable<int> SelledSinglePrice { get; set; }
        public Nullable<System.DateTime> SellDate { get; set; }
    }
}
